// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfvzcfmuxneqihrrqipn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmdnpjZm11eG5lcWlocnJxaXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzUxMDcsImV4cCI6MjA2NTU1MTEwN30.59I8BNfVmpp2Jzcob6OyAsXbbvf5a_Z7vloRsvyYw9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);